using Subscrio.Core.Application.DTOs;
internal static class ReferenceCalls { public static async Task CompileOnly(Subscrio.Core.Subscrio subscrio){
await subscrio.Addons.CreateAddonAsync(new("seat-pack","studio","Extra seats"));
await subscrio.Addons.UpdateAddonAsync("seat-pack",new("Extra seats"));
await subscrio.Addons.GetAddonAsync("seat-pack");
await subscrio.Addons.ListAddonsAsync("studio",50,0);
await subscrio.Addons.ArchiveAddonAsync("seat-pack");
await subscrio.Addons.UnarchiveAddonAsync("seat-pack");
await subscrio.Addons.DeleteAddonAsync("seat-pack");
await subscrio.Subscriptions.AttachAddonAsync("acme-pro","seat-pack",2);
await subscrio.Subscriptions.DetachAddonAsync("acme-pro","seat-pack");
await subscrio.Subscriptions.GetAddonsAsync("acme-pro");
await subscrio.Features.UpdateFeatureAsync("requests",new(MeteredConfig:new("monthly","hard","sum","customer")));
await subscrio.Features.GetFeatureAsync("requests");
await subscrio.Metering.GetUsageAsync("acme","studio","requests",new(RequestedUsage:2));
await subscrio.Metering.ReportUsageAsync("acme","studio","requests",2,new("request-123"));
await subscrio.Metering.ListUsageEventsAsync("acme","studio","requests",50,0);
await subscrio.Credits.GetPlanGrantAsync("pro","ai-credits");
await subscrio.Credits.GetConsumptionRuleAsync("render","ai-credits");
await subscrio.Credits.IssueDuePlanGrantsAsync(new("acme-pro"));
await subscrio.Credits.CreateCurrencyAsync(new("ai-credits","AI credits"));
await subscrio.Credits.GetCurrencyAsync("ai-credits");
await subscrio.Credits.ListCurrenciesAsync(50,0);
await subscrio.Credits.UpdateCurrencyAsync("ai-credits","AI credits");
await subscrio.Credits.ArchiveCurrencyAsync("ai-credits");
await subscrio.Credits.UnarchiveCurrencyAsync("ai-credits");
await subscrio.Credits.DeleteCurrencyAsync("ai-credits");
await subscrio.Credits.SetPlanGrantAsync("pro","ai-credits",new(100,"monthly","grant_period_end","retain"));
await subscrio.Credits.RemovePlanGrantAsync("pro","ai-credits");
await subscrio.Credits.ListPlanGrantsAsync("pro");
await subscrio.Credits.SetConsumptionRuleAsync("render","ai-credits",3);
await subscrio.Credits.RemoveConsumptionRuleAsync("render","ai-credits");
await subscrio.Credits.ListConsumptionRulesAsync("render");
await subscrio.Credits.GrantAsync(new("acme","ai-credits",100,"prepaid","purchase-123"));
await subscrio.Credits.ProcessScheduledGrantsAsync("acme");
await subscrio.Credits.GetBalanceAsync("acme","ai-credits");
await subscrio.Credits.ListBalancesAsync("acme");
await subscrio.Credits.CanConsumeAsync(new("acme","render",2));
await subscrio.Credits.ConsumeAsync(new("acme","render",2,"render-123"));
await subscrio.Credits.AdjustAsync(new("acme","ai-credits",-2,"correction","adjust-123"));
await subscrio.Credits.ListGrantsAsync("acme","ai-credits");
await subscrio.Credits.GetOperationAsync("acme","render-123");
await subscrio.Credits.ListLedgerEntriesAsync("acme","ai-credits");
}}
